### ISSUE TITLE
Core: Tracking issue of website v3

### ISSUE THREAD

**Issue by SonMooSans** [yeecord/website#111]
We planned to have a big update after Nextra officially supports headless CMS

- [ ] ~~Migrate to headless CMS such as Strapi~~
- [x] Redesign of Docs Theme 
- [x] Improve load speed
- [x] New contribution guide
- [ ] ~~Transfer to monorepo (Turbo or Lerna)~~
